services:
  db:
    image: postgres:15
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    env_file: .env
    environment:
      PIPENV_VENV_IN_PROJECT: "1"
    volumes:
      - .:/app
    command: python main.py

volumes:
  pgdata:
